# Generated by Django 3.1.4 on 2021-01-04 17:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20210104_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='request',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
