# Generated by Django 3.1.4 on 2021-01-08 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_order_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='request',
            field=models.TextField(blank=True, null=True),
        ),
    ]
