# Generated by Django 3.1.4 on 2021-01-10 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bag', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_status',
            field=models.CharField(max_length=5),
        ),
    ]
