# Generated by Django 3.1.4 on 2021-01-18 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210109_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='spice_index',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
