# Generated by Django 3.1.4 on 2021-02-06 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_availability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
    ]
